{% set name = "astropy-healpix" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astropy_healpix-{{ version }}.tar.gz
  sha256: 88c384eb4322997a58de8938e91ac9ff90f6a2b6cb2ae23e2169c7405add3ad8

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - setuptools-scm
    - extension-helpers
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - astropy >=3

test:
  requires:
    - pytest-astropy
  imports:
    - astropy_healpix
  commands:
    - pip check
    # The test suite runs in <20 seconds so is worth running here to
    # make sure there are no issues with the C/Cython extensions
    - pytest --pyargs astropy_healpix
  requires:
    - pip

about:
  home: https://github.com/astropy/astropy-healpix
  summary: BSD-licensed HEALPix for Astropy
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - beckermr
    - astrofrog
