{% set name = "astropy-healpix" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f520d83abe8215d3e8e1a37b2bd91171ee36a6f55f110d5a2db863d75d81b3b7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py < 310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - setuptools
    - setuptools_scm
    - extension-helpers
    - wheel
  run:
    - python
    - astropy-base >=3

test:
  requires:
    - hypothesis
    - pytest-astropy
  imports:
    - astropy_healpix
  commands:
    - pytest --pyargs astropy_healpix

about:
  home: http://github.com/astropy/astropy-healpix
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: BSD-licensed HEALPix for Astropy
  description: BSD-licensed HEALPix for Astropy
  doc_url: https://astropy-healpix.readthedocs.io
  dev_url: https://github.com/astropy/astropy-healpix

extra:
  recipe-maintainers:
    - lpsinger
    - beckermr
    - astrofrog
