{% set name = "astropy-healpix" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d1816587a6049188e2aa2e9f001259de3f8ba158f04b93b506bb847264007f6e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py < 310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - setuptools
    - setuptools_scm
    - extension-helpers
    - wheel
  run:
    - python
    - astropy-base >=3

test:
  requires:
    - pytest-astropy
  imports:
    - astropy_healpix

about:
  home: http://github.com/astropy/astropy-healpix
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: BSD-licensed HEALPix for Astropy
  description: BSD-licensed HEALPix for Astropy
  doc_url: https://astropy-healpix.readthedocs.io
  dev_url: https://github.com/astropy/astropy-healpix

extra:
  recipe-maintainers:
    - beckermr
    - astrofrog
