{% set name = "astropy-healpix" %}
{% set version = "0.5" %}
{% set sha256 = "5ae15da796a840f221fb83e25de791e827b6921bc21a365d99bc1a59c7c0cdad" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt --offline --no-git
  skip: true  # [py27]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy         # [not (win and (py35 or py36))]
    - numpy         # [win and (py35 or py36)]
  run:
    - python
    - {{ pin_compatible('numpy') }}   # [not (win and (py35 or py36))]
    - {{ pin_compatible('numpy') }}   # [win and (py35 or py36)]
    - astropy >=2.0

test:
  requires:
    - pytest-astropy
  imports:
    - astropy_healpix

about:
  home: http://github.com/astropy/astropy-healpix
  license: BSD
  license_family: BSD
  license_file: LICENSE.md
  summary: BSD-licensed HEALPix for Astropy
  description: BSD-licensed HEALPix for Astropy
  doc_url: https://astropy-healpix.readthedocs.io
  dev_url: https://github.com/astropy/astropy-healpix

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - cdeil
