{% set name = "astropy-healpix" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 056fa6ed9396bedc771d374d877cde83d9460a3f62a78fe05dbf9ba03940323a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --install-option="--offline" --install-option="--no-git"
  skip: true  # [py <= 27]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - setuptools_scm
    - extension-helpers
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - astropy >=2.0

test:
  requires:
    - pytest-astropy
  imports:
    - astropy_healpix

about:
  home: http://github.com/astropy/astropy-healpix
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: BSD-licensed HEALPix for Astropy
  description: BSD-licensed HEALPix for Astropy
  doc_url: https://astropy-healpix.readthedocs.io
  dev_url: https://github.com/astropy/astropy-healpix

extra:
  recipe-maintainers:
    - beckermr
    - astrofrog-conda-forge
