# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gc6um2nwTjTjJ9LjkssndYs54VVYFwVSWia5WGE/YlILS8nBRGoHBWUmr2+us6br8AsDJR3j3WpQMyRLSRRR+pG8C/kX3qmlonGYe7XipS2fc4EhBHnBh9Ew9eRIZwoZqWAj5HePfm/86hQ8PO+vDvz2n3RF5KmF38YaEadG5YDgQngt408e6EQOeI4CCGy9eX2zoaWebRdKDoFoNkDThie0xyby9L9hVfQoiDx/cNGZM4UwJdUAe1xLy8nognjxgQ+AB9y0hsN92LIhpI1HhWi7hB8Y7lhgR2G/OjLkj1MMq+Xc1feXJGCB4XK9gqvghazJec7/mz+mqr0BSXjvpyxpEuV5zp0MV4wwc7Rd4eQPZZFXS/iqxm4YY/1dJoTJoxlfY0JwH5/OplD665qX6xDU0zgy13EoSIXe/LBCG079aO7G8nWy/U+bKFeOUPoF+wJVzpTlkgE2SmUUqISRlBp+YgJxtlccEHsFFMU2psbxuaGFNuk80amQ9xcXi2iep81p5YrQ7QsfUDYfkdAIx1No/5zascNXMePdOCqe2af6Bpya5sHaczzQWcPzU8P0o2hV/lhSjLMQc5nV3DgBOoKPhGQzD/XkRM5W46VeeKc4jDSwuDDWuTZYTmOYg5dAIhzL9MvMy7ZDJ0qdzRI4VnCnTLL1rv1ZZpdn/ANqUN8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
