appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: gc6um2nwTjTjJ9LjkssndYs54VVYFwVSWia5WGE/YlILS8nBRGoHBWUmr2+us6br8AsDJR3j3WpQMyRLSRRR+pG8C/kX3qmlonGYe7XipS2fc4EhBHnBh9Ew9eRIZwoZqWAj5HePfm/86hQ8PO+vDvz2n3RF5KmF38YaEadG5YDgQngt408e6EQOeI4CCGy9eX2zoaWebRdKDoFoNkDThie0xyby9L9hVfQoiDx/cNGZM4UwJdUAe1xLy8nognjxgQ+AB9y0hsN92LIhpI1HhWi7hB8Y7lhgR2G/OjLkj1MMq+Xc1feXJGCB4XK9gqvghazJec7/mz+mqr0BSXjvpyxpEuV5zp0MV4wwc7Rd4eQPZZFXS/iqxm4YY/1dJoTJoxlfY0JwH5/OplD665qX6xDU0zgy13EoSIXe/LBCG079aO7G8nWy/U+bKFeOUPoF+wJVzpTlkgE2SmUUqISRlBp+YgJxtlccEHsFFMU2psbxuaGFNuk80amQ9xcXi2iep81p5YrQ7QsfUDYfkdAIx1No/5zascNXMePdOCqe2af6Bpya5sHaczzQWcPzU8P0o2hV/lhSjLMQc5nV3DgBOoKPhGQzD/XkRM5W46VeeKc4jDSwuDDWuTZYTmOYg5dAIhzL9MvMy7ZDJ0qdzRI4VnCnTLL1rv1ZZpdn/ANqUN8=}
